# Generated by Django 5.1.3 on 2024-11-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisis',
            name='categorias_lexicas',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='analisis',
            name='palabras_frecuentes',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='analisis',
            name='relaciones_semanticas',
            field=models.JSONField(default=dict),
        ),
    ]
